### ISSUE TITLE
API Wallet Integration

### ISSUE THREAD

**Issue by placer14** [OpenBazaar/openbazaar-go#1015]
Placeholder to track API wallet integration progress.

Scope overview:
- [x] modify config to facilitate API wallet
- [x] instantiate API wallet for node
- [x] (optional) export current wallets to external repos for later use in plugin interface
- [x] update and migrate wallet db tables to support multiple coins 
- include Ethereum API wallet into API multiwallet
   - [x] (https://github.com/OpenBazaar/multiwallet/pull/4) update multiwallet to use shifted wallet-interface
   - [x] integrate Ethereum API wallet
- [x] (https://github.com/OpenBazaar/openbazaar-go/issues/1098) update /ob/config API call to include list of wallets
- update API interfaces to support different coins on a per-transaction basis
    - Wallet API
        - [x] (https://github.com/OpenBazaar/openbazaar-go/issues/1099) GET wallet/address
        - [x] (https://github.com/OpenBazaar/openbazaar-go/issues/1100) GET wallet/balance
            - if no coin type is sent, all coin balances should be returned in an object keyed with the coin codes.
        - [x] (https://github.com/OpenBazaar/openbazaar-go/issues/1106) GET wallet/transactions
        - [x] (https://github.com/OpenBazaar/openbazaar-go/issues/1100) GET wallet/status
        - [x] (https://github.com/OpenBazaar/openbazaar-go/issues/1101) GET wallet/fees
        - [x] (https://github.com/OpenBazaar/openbazaar-go/issues/1102) POST wallet/spend
        - [x] (https://github.com/OpenBazaar/openbazaar-go/issues/1103) POST wallet/bumpfee
        - [x] (https://github.com/OpenBazaar/openbazaar-go/issues/1104) POST wallet/resyncblockchain
        - [x] (https://github.com/OpenBazaar/openbazaar-go/issues/1105) the wallet socket for new transactions will need to send a coin type.
        - [x] (https://github.com/OpenBazaar/openbazaar-go/issues/1105) the wallet socket for first confirmation on a transaction will need to send a coin type (Q: https://github.com/OpenBazaar/openbazaar-go/issues/1015#issuecomment-414324612)
        - [x] (https://github.com/OpenBazaar/openbazaar-go/issues/1108) the walletUpdate socket will need to return an object of data keyed to coin types or separate socket data would need to be delivered for each wallet.
    - Listing APIs
        - [x] (https://github.com/OpenBazaar/openbazaar-go/issues/1109) GET ob/listings
            - each listing will need a list of accepted coins (maybe in price.acceptedCurrencies?)
        - [x] (https://github.com/OpenBazaar/openbazaar-go/issues/1110) GET ob/listing
            - a list of accepted coins should be returned
        - [x] (https://github.com/OpenBazaar/openbazaar-go/issues/1111) POST ob/listing
            - a list of accepted coins should be sent.
    - Settings
        - [x] (https://github.com/OpenBazaar/openbazaar-go/issues/1137) GET ob/settings
            - return a list of preferred coins. This will be used to auto-populate new listings.
        - [x] (https://github.com/OpenBazaar/openbazaar-go/issues/1138) POST ob/settings
            - accept a list of preferred coins.
    - Profile
        - [x] (https://github.com/OpenBazaar/openbazaar-go/issues/1139) GET ob/profile
            - moderatorInfo should return a list of preferred coins (moderatorInfo.acceptedCurrencies)
        - POST/PATCH ob/profile
            - [x] (https://github.com/OpenBazaar/openbazaar-go/issues/1140) moderatorInfo should accept a list of preferred coins (moderatorInfo.acceptedCurrencies)
            - [ ] (https://github.com/OpenBazaar/openbazaar-go/issues/1141) when the list of moderators is changed, each one should be validated to make sure it supports the vendor's coins (ie, if the moderator is using a plug-in SPV wallet with a coin the vendor doesn't have).
    - Moderators
        -  GET ob/moderators 
            - [ ] (https://github.com/OpenBazaar/openbazaar-go/issues/1142) should accept a list of coins and return only moderators that accept at least one of them based on their moderatorInfo.acceptedCurrencies data.
            - [x] (https://github.com/OpenBazaar/openbazaar-go/issues/1143) should accept a parameter for full match. If true, only return moderators that accept all of the coins in the list of coins sent.
- [x] profile.moderatorInfo.acceptedCurrencies reflects the same set as values from this task: `GET full list of available currencies`

Sidetasks:

 - [x] Discuss and resolve the backup API solution

**Comment by jjeffryes** [comment]
Can we add a task to have profile.moderatorInfo.acceptedCurrencies automatically populated with all the coins in the user's wallet when their node is created?

Since we decided to not expose that in the client, it makes sense to me to have it just done at node creation. Other clients could expose the ability to change that list if they wanted.

**Comment by placer14** [comment]
@jjeffryes @rmisio Do you know if this task use a different notification type than usual transaction sockets?
`the wallet socket for first confirmation on a transaction will need to send a coin type`

**Comment by jjeffryes** [comment]
It's an existing socket message, wouldn't it be whatever the existing message is?

**Comment by placer14** [comment]
I'm trying to determine if these two tasks share the same notification type internally:
`the wallet socket for first confirmation on a transaction will need to send a coin type` and `the wallet socket for new transactions will need to send a coin type.` I thought maybe the type is delivered in the payload in the socket and you might know from that. I can investigate.

**Comment by jjeffryes** [comment]
There's a walletUpdate socket message:
`{walletUpdate: {confirmed: 0, height: 537657, unconfirmed: 0}}`

The first confirmation message:
`{
    "wallet": {
        "address": "",
        "canBumpFee": true,
        "confirmations": 1,
        "height": 1384638,
        "memo": "",
        "orderId": "",
        "status": "PENDING",
        "thumbnail": "",
        "timestamp": "0001-01-01T00:00:00Z",
        "txid": "f575e6cc0a88ba7609672cbf3736e2a537ad405bc882453a446b71acbf09823f",
        "value": 155106
    }
}`

(in this case there was no orderId because I just transferred funds directly between two nodes)

**Comment by cpacia** [comment]
This is closed
