### ISSUE TITLE
Tracking IPFS changes needed to get off of a fork

### ISSUE THREAD

**Issue by cpacia** [OpenBazaar/openbazaar-go#1440]
The following three issues are open in go-ipfs. We've currently patched our vendor package to address these issues. If we can get them fixed upstream then we are most of the way to getting off of using a fork.

- [ ] [namesys/routing.go imports dht package preventing dht.Quorum() from being used with a custom routing option #5957](https://github.com/ipfs/go-ipfs/issues/5957)

- [ ] [First round bootstrap #5953](https://github.com/ipfs/go-ipfs/issues/5953)

- [ ] [Disable DNSResolver option #5945](https://github.com/ipfs/go-ipfs/issues/5945)

The following two issues are issues with our protocol design that we're currently trying to fix. Once most of our network upgrades we can stop patching go-ipfs in these areas.

- [ ] The latest version of go-ipfs broke compatibility with the hashed ed25519 keys that we've been using. We've had to patch the code to fix this. However, we want to be able to transition off of using hashed keys in favor of inline keys. Once we do this then we can stop patching go-ipfs in this regard. This assumes go-ipfs continues to remain compatible with inline keys  [libp2p/specs#138](https://github.com/libp2p/specs/issues/138)

- [ ] ob-go issue #1438
