### ISSUE TITLE
Migrate JSON API timestamps to RFC3339

### ISSUE THREAD

**Issue by placer14** [OpenBazaar/openbazaar-go#1571]
As part of the fix required to resolve #1545, the timestamps used in the JSON API need to be consistently represented/consumed.

Todo:

- [x] confirm desktop and mobile can consume RFC3339
- [x] confirm desktop and mobile can send RFC3339-parseable value
- [x] identify and apply format changes to all the areas of the API where the timestamp is used
  - [x] ~POST|GETPost (create `repo.SocialPost` to handle presentation concerns (postponed #1594))~
  - [x] POSTBumpFee
  - [x] GETChatMessages
  - [x] GETChatConversations
  - [x] GETTransactions
  - [x] GETNotifications
  - [x] ~GETOrder (create local representations for `pb.OrderRespApi` (postponed #1598))~
  - [x] ~POSTFetchRatings (create local representations for `pb.Rating` (postponed #1599))~
- [x] update JSON API doc examples and mentions to reflect new timestamp format
- [x] review other docs to ensure timestamps mentioned don't also need updates (https://github.com/OpenBazaar/official_docs/pull/10)

Aside from JSON API doc examples being updated (which will eventually be included in tests), it's not clear what other test improvements we might want to include in these changes.

**Comment by placer14** [comment]
@drwasho @jjeffryes Will the mobile and desktop client be able to consume this timestamp format properly: `2006-01-02T15:04:05.999999999Z07:00`? The plan is to update the JSON API to use this format throughout (which supports the higher resolution). (This is called RFC3339 if that helps you determine support.) I'm also curious what format each client uses to POST timestamps. It looks like the `POST /ob/post` and `POST /ob/chat` accepts a timestamp. Discussions with @jjeffryes suggest the desktop will easily support `2006-01-02T15:04:05Z07:00` (that is the same as RFC3339 minus the decimal after the seconds). Would like for the formats to be consistent throughout the API, but that can come later if it's too big of an ask all at once. Please let me know.
