### ISSUE TITLE
v1.0-alpha Milestone TODO

### ISSUE THREAD

**Issue by cpacia** [OpenBazaar/openbazaar-go#220]
API

- [x] Wrap IPFS API with `ob` endpoints. Requires design session.
- [x] Provide local API to fetch own listings. #204
- [ ] Switch GET listing API nested listing return from list to object.
- [ ] Include hash in return of listing fetch. #201
- [ ] Create GET sales, purchases, and cases endpoints.
- [x] If a user has no listing the listings API returns a 404. #183
- [ ] Create ratings API endpoint
- [ ] Sanitize all API responses

LISTINGS

- [ ] Add Language to Listings #143
- [ ] Design/create listing drafts
- [ ] Add aggregate rating of a listing to the listing index. #160

ORDERS

- [x] Finish dispute resolution #180 
- [ ] Implement moderator change requests
- [ ] Auto send digital goods

CHAT

- [x] Build chat database table
- [x] Build chat network messages
- [x] Build chat API calls

NOTIFICATIONS

- [x] Build notifications database table
- [x] Build notifications API calls
- [ ]  Implement SMTP notifications

SPVWALLET

- [x] Improve DNS seed/address cache handling
- [ ] Evict transactions on blockchain reorg
- [x] General code cleanup/refactoring
- [ ] Shitload of tests

CHANNELS

- [ ] Design channel JSON schema
- [ ] Maybe create API endpoint

TOR

- [ ] Document/fix all IPFS libraries with compilation errors that are needed for Tor.
- [ ] Implement it #99 
- [ ] Make sure external API calls go out over Tor and/or create an onion proxy for those APIs.

OTHER
- [x] Create server init command to determine the state of the database encryption pw. #245

**Comment by drwasho** [comment]
@cpacia can you update this checklist when you get the chance.
