### ISSUE TITLE
[Meta] Protocol-level changes to consider before launch

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/openbazaar-go#363]
This my personal tracking list of protocol-level changes that I think should be considered and possibly addressed before the full public launch of OB2.0. After launch, modifying the OpenBazaar protocol will be expensive.

I have added a `*` next to issues that directly affect Duo. Having visibility on those ASAP would be greatly appreciated. We are happy to help where we can. I will keep this list updated.

cc @cpacia, @hoffmabc, @jackkleeman, @morebrownies, @jjeffryes, @tyler-smith, @drwasho

- [ ] #635 Coupon hash commitments
- [ ] #553* ENS proposal
- [ ] #492 Non-censurable ratings
- [ ] #483 Application-level ACKs
- [ ] #362 Signed chat messages
- [ ] #351 Cleaner pointer implementation
- [ ] #337 Communicate errors to peers
- [x] #349* Better image sizes
- [ ] #334* Configurable prefix lengths
- [x] #326* Include moderator public key
- [x] #325 Timelocked funds release
- [ ] #303* Offline message timestamps
- [ ] #297* Manual vs automatic confirmations
- [ ] #248 Specify number of confirmations for digital items
- [ ] #290 Embrace CIDv1
- [ ] #240* Decouple application PeerID from transport PeerID
- [ ] #188* Advertise several accepted currencies
- [ ] #107 Follower signatures
- [ ] [openbazaar-desktop #282](https://github.com/OpenBazaar/openbazaar-desktop/issues/282) Decouple review and fund release
- [ ] [openbazaar-desktop #331](https://github.com/OpenBazaar/openbazaar-desktop/issues/331) Amicable resolutions
- [ ] [openbazaar-desktop #280](https://github.com/OpenBazaar/openbazaar-desktop/issues/280) Partial ratings
- [ ] [openbazaar-desktop #76](https://github.com/OpenBazaar/openbazaar-desktop/issues/76) Free listings
- [ ] [openbazaar-desktop #59](https://github.com/OpenBazaar/openbazaar-desktop/issues/59) Misspayment buffer
- [ ] [openbazaar-desktop #57](https://github.com/OpenBazaar/openbazaar-desktop/issues/57) Listing language field
- [ ] [go-libp2p-kad-dht #45](https://github.com/libp2p/go-libp2p-kad-dht/issues/45)* Aggressive DHT evictions

**Comment by hoffmabc** [comment]
This link is dead.
go-libp2p-kad-dht #45* Aggressive DHT evictions
https://github.com/OpenBazaar/openbazaar-go/issues/libp2p/go-libp2p-kad-dht/issues/45

**Comment by JustinDrake** [comment]
Fixed

**Comment by yurizhykin** [comment]
@JustinDrake , all of 'openbazaar-desktop' ones seem to be dead either because of this `issues/.../issues/..` thing.

**Comment by JustinDrake** [comment]
Thanks, fixed!
