### ISSUE TITLE
Updates to Support Crypto Listings

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-go#876]
To support a listing type for cryptocurrencies, we would need the following changes/features:

- There should be a cryptocurrency listing type.
- That type should accept a field for the currency code of the cryptocurrency being sold, or use the existing currency field for that.
- The price field should be left blank, or accept an amount of 0. The listing should always use the current value of that cryptocurrency converted into the order cryptocurrency instead (ie: if ETH is being sold on a node using BTC, the price should be ETH converted to BTC based on the current exchange rate).
- The quantity field is assumed to represent 0.00000001 of one whole coin.
- When the listing is saved, it should reject any fields that are not used for crypto listings if they are sent, such as shipping data, variants, or coupons.
- When a purchase is made of a cryptocurrency type listing, the contract should have a delivery address field, which represents the address the seller should send the purchased funds to.
- When an order is fulfilled, the call should accept a transaction ID, which represents the ID of the transaction where the seller sent the funds to the buyer's address. This should be shown in the contract.

## Data

The following changes to the data are expected:

- [x] POST/PUT ob/listing (https://github.com/OpenBazaar/openbazaar-go/issues/885)
- [x] POST ob/purchase (https://github.com/OpenBazaar/openbazaar-go/issues/886)
- [x] GET ob/order (https://github.com/OpenBazaar/openbazaar-go/issues/892)
- [x] POST ob/orderfulfillment (https://github.com/OpenBazaar/openbazaar-go/issues/893)
- [x] Cryptocurrency listing should define coin divisibility (https://github.com/OpenBazaar/openbazaar-go/issues/888)
 - [x] Publish semi-realtime listing inventory availability for vendor to IPFS (https://github.com/OpenBazaar/openbazaar-go/issues/875 )
